# ✅ Name of the Workflow
name: Pipeline CI/CD sonarqube-code-quality-scan-job.

# ✅ Trigger this workflow on pull request to main branch.
on:
  pull_request:
    branches:
      - main

# ✅ Global Environment Variables
env:
  BUILD_NUMBER: ${{ github.run_number }}  # Unique build number for the pipeline run
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:${{ github.run_number }}

jobs:

  sonarqube-code-quality-scan-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Source Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # v8.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
    
  trivy-image-security-scan-job:
    runs-on: ubuntu-latest
    steps: 

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Download and install Trivy
        run: |
          curl -sSL https://github.com/aquasecurity/trivy/releases/download/v0.29.0/trivy_0.29.0_Linux-64bit.tar.gz -o trivy.tar.gz
          tar xzvf trivy.tar.gz
          sudo mv trivy /usr/local/bin/
          trivy --version

      - name: Run Trivy Docker image vulnerability scan
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          trivy image ${{ env.IMAGE_NAME }}

         # trivy fs . 

